const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const fields = ['productName','description','price','delivery','audience','benefit'];
let ads = JSON.parse(localStorage.getItem('sirajiadspy-ads') || localStorage.getItem('addekh-ads') || '[]');

function product(){ return Object.fromEntries(fields.map(id => [id, $(`#${id}`).value.trim()])); }
function save(){ localStorage.setItem('sirajiadspy-product', JSON.stringify(product())); localStorage.setItem('sirajiadspy-ads', JSON.stringify(ads)); updateCompletion(); }
function restore(){ const p=JSON.parse(localStorage.getItem('sirajiadspy-product')||localStorage.getItem('addekh-product')||'{}'); fields.forEach(id=> $(`#${id}`).value=p[id]||''); renderAds(); updateCompletion(); }
function showStep(n){ $$('.panel').forEach((p,i)=>p.classList.toggle('active',i===n-1)); $$('.step').forEach((p,i)=>p.classList.toggle('active',i===n-1)); location.hash='workspace'; if(n===2) prepResearch(); if(n===3) generate(); }
function updateCompletion(){ const done=fields.filter(id=>$(`#${id}`).value.trim()).length; $('.completion').textContent=`${Math.round(done/fields.length*100)}% complete`; }
fields.forEach(id=>$(`#${id}`).addEventListener('input',save));
$$('.step').forEach(b=>b.addEventListener('click',()=>showStep(+b.dataset.step)));

$('#imageInput').addEventListener('change', e=>{ const f=e.target.files[0]; if(!f)return; if(f.size>8e6){alert('Please choose an image under 8 MB.');return} const reader=new FileReader(); reader.onload=()=>{ $('#preview').src=reader.result; $('#preview').hidden=false; $('#uploadPrompt').hidden=true; }; reader.readAsDataURL(f); });
$('#toResearch').onclick=()=>{ if(!$('#productName').value.trim()){ $('#productName').focus(); alert('Add a product name to build the research plan.'); return;} save(); showStep(2); };
$('#toLab').onclick=()=>showStep(3);
$('#demoBtn').onclick=()=>{ const demo={productName:'Men’s Everyday Sneaker',description:'Lightweight knit sneaker for office commutes and casual use',price:'1490',delivery:'80',audience:'Men 20–35 in Dhaka; students and office commuters',benefit:'Soft all-day comfort with 7-day size exchange'}; fields.forEach(id=>$(`#${id}`).value=demo[id]); ads=[{page:'Urban Step BD',days:23,format:'UGC / selfie',hook:'Office থেকে hangout—এক জুতাতেই সব?',angle:'One versatile shoe for the whole day',comment:'Size change করা যাবে?',url:''},{page:'WalkEasy',days:17,format:'Product demo',hook:'এই sole-টা এত soft কেন দেখুন',angle:'Visible comfort proof at an accessible price',comment:'Actual colour same হবে?',url:''},{page:'Shoe Box Dhaka',days:8,format:'Unboxing / POV',hook:'৳1500-এর নিচে premium look',angle:'Premium appearance without premium price',comment:'Cash on delivery আছে?',url:''}]; save(); showStep(1); };

function prepResearch(){ const p=product(); const terms=[p.productName,p.audience.split(',')[0],p.benefit.split('+')[0]].filter(Boolean); $('#searchTerms').textContent=terms.join(' · ')||'Add a product first'; const q=encodeURIComponent(p.productName||'shoes'); $('#libraryLink').href=`https://www.facebook.com/ads/library/?active_status=active&ad_type=all&country=BD&q=${q}&search_type=keyword_unordered`; renderAds(); }
$('#addAd').onclick=()=>$('#adDialog').showModal();
$('#saveAd').onclick=(e)=>{ const page=$('#adPage').value.trim(), hook=$('#adHook').value.trim(); if(!page||!hook){e.preventDefault(); alert('Add the competitor name and opening hook.');return} ads.unshift({page,days:+$('#adDays').value||1,format:$('#adFormat').value,hook,angle:$('#adAngle').value.trim(),comment:$('#adComment').value.trim(),url:$('#adUrl').value.trim()}); save(); renderAds(); ['adPage','adDays','adHook','adAngle','adComment','adUrl'].forEach(id=>$(`#${id}`).value=''); };
function renderAds(){ $('#adCount').textContent=ads.length; const box=$('#adsList'); if(!ads.length){box.innerHTML='<div class="empty"><span>◎</span><b>No ads saved yet</b><p>Open Ad Library and add the strongest active ads you find.</p></div>';return} box.innerHTML=ads.map((a,i)=>`<article class="ad-item"><div class="ad-rank">${String(i+1).padStart(2,'0')}</div><div><h4>${esc(a.page)} · ${esc(a.format)}</h4><p>“${esc(a.hook)}”${a.angle?` — ${esc(a.angle)}`:''}</p></div><div><span class="badge ${a.days>=15?'strong':''}">${a.days} days</span><button aria-label="Remove" data-remove="${i}">×</button></div></article>`).join(''); $$('[data-remove]').forEach(b=>b.onclick=()=>{ads.splice(+b.dataset.remove,1);save();renderAds()}); }
function esc(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

function generate(){ const p=product(); const name=p.productName||'your product'; const price=p.price?`৳${Number(p.price).toLocaleString('en-BD')}`:'an accessible price'; const objections=ads.map(a=>a.comment).filter(Boolean); const angles=ads.map(a=>a.angle).filter(Boolean); const long=ads.filter(a=>a.days>=15).length; const confidence=Math.min(95,25+ads.length*7+long*3); $('#confidence').textContent=`${confidence>=70?'Strong':confidence>=45?'Useful':'Starter'} · ${confidence}%`; $('#confidenceBar').style.width=confidence+'%'; $('#strategySubtitle').textContent=`Evidence-led starting points for ${name}.`;
  const pain=objections[0]||`Will ${name} deliver the promised result without purchase risk?`; $('#pain').textContent=`“${pain}”`;
  const benefit=p.benefit||'a clear, low-risk result'; $('#whitespace').textContent=angles.length?`${benefit}—shown with proof, not just claimed.`:`Make ${benefit} visible in the first 3 seconds.`; $('#whitespaceWhy').textContent=angles.length?`Most saved ads lean on “${angles[0]}”. Differentiate with demonstration and risk reversal.`:'Add competitor ads to identify a more evidence-based gap.';
  const offer=p.price && +p.price>=999?`Free delivery + ${benefit.toLowerCase()}`:`COD + ${benefit.toLowerCase()}`; $('#offer').textContent=offer; $('#offerWhy').textContent=p.delivery?`Removes the ৳${p.delivery} delivery objection and reduces purchase risk`:'Combines convenience with purchase reassurance';
  const hooks=[['Question',`Still compromising on ${name.toLowerCase()} for daily use?`],['Negative',`3 reasons this ${name.toLowerCase()} may NOT be for you.`],['Proof',`Watch this before spending ${price} on ${name.toLowerCase()}.`],['Result',`From first use to all-day comfort—here’s the real test.`],['Bangla mix',`${name} কিনবেন? আগে এই 3টা জিনিস check করুন.`]]; $('#hooks').innerHTML=hooks.map(([t,h])=>`<article class="hook"><span>${t}</span><p>${esc(h)}</p><button data-copy="${esc(h)}">□</button></article>`).join(''); $$('[data-copy]').forEach(b=>b.onclick=()=>copy(b.dataset.copy));
  $('#briefTitle').textContent=`UGC: ${name} — problem → proof → offer`; $('#shotList').innerHTML=[`0–3s: Say “${hooks[0][1]}” while holding the product close to camera.`,`3–8s: Show the problem in a familiar Bangladesh daily-life setting.`,`8–17s: Demonstrate ${benefit}; use a close-up instead of a generic claim.`,`17–24s: Address “${objections[0]||'Will I get what I see?'}” with policy, proof or comparison.`,`24–30s: Present ${offer}, COD and one clear call to action.`].map(x=>`<li>${esc(x)}</li>`).join(''); }
function strategyText(){ return `${$('#strategySubtitle').textContent}\n\nAUDIENCE TENSION\n${$('#pain').textContent}\n\nWHITE-SPACE ANGLE\n${$('#whitespace').textContent}\n\nOFFER\n${$('#offer').textContent}\n\nHOOKS\n${$$('.hook p').map((p,i)=>`${i+1}. ${p.textContent}`).join('\n')}\n\nSHOOTING BRIEF\n${$$('#shotList li').map((p,i)=>`${i+1}. ${p.textContent}`).join('\n')}`; }
function copy(t){navigator.clipboard.writeText(t).then(()=>{ $('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1600)})}
$('#copyAll').onclick=()=>copy(strategyText()); $('#copyBrief').onclick=()=>copy($$('#shotList li').map((x,i)=>`${i+1}. ${x.textContent}`).join('\n')); $('#resetBtn').onclick=()=>{if(confirm('Clear the current product and saved evidence?')){localStorage.removeItem('sirajiadspy-product');localStorage.removeItem('sirajiadspy-ads');localStorage.removeItem('addekh-product');localStorage.removeItem('addekh-ads');location.reload()}};
restore();
