import OpenAI from 'openai';
import {z} from 'zod';
import type {CreativeBrief} from './types';
import {geminiJson} from './gemini';

export const CreativeInputSchema=z.object({product:z.string().trim().min(2).max(120),description:z.string().trim().min(8).max(1200),audience:z.string().trim().min(2).max(300),price:z.string().trim().max(80).optional().default(''),benefit:z.string().trim().min(2).max(300),offer:z.string().trim().max(300).optional().default(''),tone:z.enum(['Bangla','Bangla + English','Banglish','English']).default('Bangla + English')});
const BriefSchema=z.object({strategy:z.string(),hooks:z.array(z.string()).length(5),copies:z.array(z.object({name:z.string(),hook:z.string(),headline:z.string(),primaryText:z.string(),cta:z.string()})).length(3),formats:z.array(z.string()).min(3).max(5),shotList:z.array(z.string()).min(5).max(7),testPlan:z.array(z.string()).min(3).max(5),imagePrompt:z.string()});
export type CreativeInput=z.infer<typeof CreativeInputSchema>;

export async function generateCreative(input:CreativeInput):Promise<{brief:CreativeBrief;mode:'gemini'|'openai'|'demo'}>{
 const language=input.tone==='Bangla'?'Write every customer-facing hook, headline, primary text, strategy and shot instruction in natural Bengali script. Keep only unavoidable brand names and common CTA terms in English.':input.tone==='Bangla + English'?'Write primarily in natural Bengali script, mixed with short familiar English marketing words used in Bangladesh (for example: fresh, confidence, office, gym, COD). Do not write Bengali words using English letters.':input.tone==='Banglish'?'Write conversational Banglish using English letters, as Bangladesh ecommerce sellers speak online.':'Write all output in clear English for a Bangladesh audience.';
 const prompt=`You are a performance creative strategist for Bangladesh ecommerce. Use only supplied facts; never invent reviews, sales, certifications or outcomes. LANGUAGE RULE: ${language} Apply this language rule to strategy, all 5 hooks, all 3 copies, formats, shot list and test plan. Return exactly 5 hooks, exactly 3 copy directions, 3-5 formats, 5-7 shot-list steps, 3-5 test steps and one safe image prompt.\n\n${JSON.stringify(input)}`;
 if((process.env.AI_PROVIDER||'gemini')==='gemini'&&process.env.GEMINI_API_KEY)return{brief:await geminiJson(prompt,BriefSchema),mode:'gemini'};
 if(!process.env.OPENAI_API_KEY){if(process.env.GEMINI_API_KEY)return{brief:await geminiJson(prompt,BriefSchema),mode:'gemini'};return{brief:fallbackCreative(input),mode:'demo'}};
 const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
 const response=await client.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',input:prompt,text:{format:{type:'json_schema',name:'creative_brief',strict:true,schema:z.toJSONSchema(BriefSchema)}}});
 return{brief:BriefSchema.parse(JSON.parse(response.output_text)),mode:'openai'};
}

export function fallbackCreative(i:CreativeInput):CreativeBrief{const offer=i.offer||'COD available — confirm details before ordering';return{strategy:`Lead with the customer problem, demonstrate ${i.benefit.toLowerCase()}, then reduce purchase risk with ${offer}.`,hooks:[`${i.audience}: still looking for ${i.benefit.toLowerCase()}?`,`Before buying ${i.product}, check this one detail.`,`The simple reason your current option may not work.`,`Watch ${i.product} solve the everyday problem in 20 seconds.`,`কম ঝামেলায় ${i.benefit} — কীভাবে দেখুন।`],copies:[{name:'Problem → proof',hook:`Still struggling to get ${i.benefit.toLowerCase()}?`,headline:`Meet ${i.product}`,primaryText:`See the problem, the product demonstration and the result before you decide. ${offer}.`,cta:'Shop now'},{name:'Banglish UGC',hook:`${i.product} কেনার আগে এই demo-টা দেখুন`,headline:`Everyday use, made simpler`,primaryText:`Real-life use দেখুন—${i.description} Main benefit: ${i.benefit}. ${offer}.`,cta:'Order now'},{name:'Offer-led',hook:`A clearer way to get ${i.benefit.toLowerCase()}`,headline:i.offer||`${i.product} for everyday use`,primaryText:`Built for ${i.audience}. Price: ${i.price||'ask for today’s price'}. ${offer}.`,cta:'Learn more'}],formats:['UGC selfie problem-to-solution','Hands-only product demonstration','Static 4:5 benefit card','Comment-reply objection video'],shotList:['0–3s: Show the problem and put the hook in large captions','3–7s: Hold or reveal the product clearly','7–15s: Demonstrate the main use in one continuous phone shot','15–21s: Show the benefit without exaggerated claims','21–27s: State price, offer and purchase conditions','27–32s: One direct call to action'],testPlan:['Test all five hooks with the same body and offer','Run one creative per ad set and avoid edits for 48 hours','Review after about 2,000 impressions; prioritize link CTR and qualified actions','Keep the top two, then test offer or proof—not everything at once'],imagePrompt:`A clean vertical 4:5 ecommerce ad for ${i.product}, designed for ${i.audience}, visually communicating ${i.benefit}, natural daylight, realistic product photography, deep blue and soft sky palette, space for Bangla headline, no fake badges, no invented testimonials, no logos.`};}
