import type { Ad } from './types';
export const demoAds:Ad[]=[
{id:'stepfresh-23',pageName:'StepFresh Bangladesh',headline:'জুতার গন্ধ? 10 সেকেন্ডে fresh',adText:'Office, gym বা daily shoes—এক spray-তেই দীর্ঘ সময় fresh feel. COD available.',cta:'Shop Now',creativeType:'VIDEO',thumbnailUrl:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',landingUrl:'https://example.com/stepfresh',country:'BD',daysActive:23,likes:184,comments:31,shares:19,signalScore:89,firstSeenAt:'2026-07-19',sourceUrl:'https://www.facebook.com/ads/library/',angle:'Remove shoe odour without washing',hook:'জুতা খুলতে ভয় লাগে?',verified:true},
{id:'urbankicks-18',pageName:'Urban Kicks BD',headline:'All-day comfort under ৳1,500',adText:'From office to evening adda. Lightweight knit, soft sole, 7-day size exchange.',cta:'Send Message',creativeType:'VIDEO',thumbnailUrl:'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=900&q=80',landingUrl:'https://example.com/shoes',country:'BD',daysActive:18,likes:122,comments:24,shares:8,signalScore:82,firstSeenAt:'2026-07-24',angle:'Premium comfort without premium price',hook:'সারাদিন জুতা পরে পা ব্যথা?',verified:true},
{id:'mango-14',pageName:'Rajshahi Fresh',headline:'Tree to Dhaka in 12 hours',adText:'Chemical-free seasonal mango. Check before payment with COD across Dhaka.',cta:'Order Now',creativeType:'IMAGE',thumbnailUrl:'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=900&q=80',landingUrl:'https://example.com/mango',country:'BD',daysActive:14,likes:96,comments:18,shares:26,signalScore:73,firstSeenAt:'2026-07-28',angle:'Freshness with delivery proof',hook:'পচা আম পেয়ে delivery charge দিয়েছেন?',verified:true},
{id:'skin-9',pageName:'Glow Theory BD',headline:'A simple 2-step routine',adText:'No complicated routine. Cleanse, hydrate and protect—made for humid Bangladesh weather.',cta:'Learn More',creativeType:'CAROUSEL',thumbnailUrl:'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80',country:'BD',daysActive:9,likes:71,comments:12,shares:5,signalScore:61,firstSeenAt:'2026-08-02',angle:'Simple skincare for humid weather',hook:'10-step skincare দরকার নেই',verified:false},
{id:'bag-6',pageName:'Carry Dhaka',headline:'One bag. Every commute.',adText:'Laptop-safe, rain-resistant and clean enough for the office.',cta:'Shop Now',creativeType:'VIDEO',thumbnailUrl:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80',country:'BD',daysActive:6,likes:39,comments:7,shares:3,signalScore:48,firstSeenAt:'2026-08-05',angle:'Reliable daily commute',hook:'বৃষ্টিতে laptop নিয়ে বের হন?',verified:false},
{id:'watch-3',pageName:'Minute BD',headline:'The everyday minimal watch',adText:'Clean dial, comfortable strap, one-year service warranty.',cta:'Send Message',creativeType:'IMAGE',thumbnailUrl:'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=900&q=80',country:'BD',daysActive:3,likes:18,comments:4,shares:1,signalScore:32,firstSeenAt:'2026-08-08',angle:'Minimal style with warranty',hook:'Every outfit-এর জন্য one watch',verified:false}
];
export function getDemoAd(id:string){return demoAds.find(a=>a.id===id)}
