import OpenAI from 'openai';
import { z } from 'zod';
import type { Ad,Analysis } from './types';
const AnalysisSchema=z.object({hookType:z.string(),angle:z.string(),persona:z.string(),whyItWorks:z.array(z.string()).min(3).max(3),weaknesses:z.array(z.string()).min(2).max(2),improvedCopies:z.array(z.object({language:z.string(),hook:z.string(),headline:z.string(),copy:z.string()})).min(3).max(3),creativeIdeas:z.array(z.string()).min(3).max(5),shotList:z.array(z.string()).min(4).max(7)});
export async function analyzeAd(ad:Ad):Promise<Analysis>{
  if(!process.env.OPENAI_API_KEY) return fallbackAnalysis(ad);
  const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
  const response=await client.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',input:`You are a Bangladesh ecommerce creative strategist. Analyze only the supplied evidence. Never claim profitability.\n\n${JSON.stringify(ad)}`,text:{format:{type:'json_schema',name:'ad_analysis',strict:true,schema:z.toJSONSchema(AnalysisSchema)}}});
  return AnalysisSchema.parse(JSON.parse(response.output_text));
}
export function fallbackAnalysis(ad:Ad):Analysis{return{hookType:'Pain point + demonstration',angle:ad.angle,persona:'Bangladesh online shoppers aged 20–40 who want a clear outcome and low purchase risk',whyItWorks:[`The opening names a recognizable problem: ${ad.hook}`,'The product benefit can be demonstrated visually','COD or a clear policy reduces first-purchase anxiety'],weaknesses:['The claim needs stronger visual proof','The offer should include one specific risk reversal'],improvedCopies:[{language:'Bangla',hook:`${ad.hook} আগে এটা দেখুন`,headline:`${ad.headline} — প্রমাণসহ`,copy:`শুধু দাবি নয়—কীভাবে কাজ করে দেখুন। COD এবং সহজ support সহ আজই অর্ডার করুন।`},{language:'Banglish',hook:`Still dealing with this? ${ad.hook}`,headline:`A smarter everyday solution`,copy:`Daily problem-er simple solution. Demo দেখুন, তারপর decide করুন. COD available.`},{language:'English',hook:`Before you buy, watch this proof`,headline:`A clearer result, with less risk`,copy:`See the problem, the demonstration and the outcome before you order. Simple support and COD available.`}],creativeIdeas:['UGC selfie: problem to live demonstration','Hands-only proof test with on-screen Bangla captions','Comment-reply video addressing the top objection'],shotList:['0–3s: State the customer problem in large Bangla captions','3–8s: Show the unwanted situation close-up','8–16s: Demonstrate the product in one continuous shot','16–23s: Show the result or comparison','23–28s: Address the strongest objection','28–32s: Present offer, COD and one call to action']}}
