import{createClient}from'@supabase/supabase-js';import type{Ad,Analysis,LandingAnalysis,TikTokAd}from'./types';
export function supabaseAdmin(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Supabase is not configured');return createClient(url,key,{auth:{persistSession:false}})}
function client(){return supabaseAdmin()}
function rowToAd(r:Record<string,unknown>):Ad{const evidence=r.evidence as Record<string,unknown>|null;return{id:String(r.id),pageName:String(r.pageName||'Unknown page'),adText:String(r.adText||''),headline:String(r.headline||'Untitled ad'),cta:String(r.cta||''),creativeType:(r.creativeType==='VIDEO'||r.creativeType==='CAROUSEL'?r.creativeType:'IMAGE'),thumbnailUrl:String(r.thumbnailUrl||r.creativeUrl||''),creativeUrl:r.creativeUrl?String(r.creativeUrl):undefined,landingUrl:r.landingUrl?String(r.landingUrl):undefined,landingAnalysis:r.landingAnalysis as LandingAnalysis|undefined,country:String(r.country||'BD'),daysActive:Number(r.daysActive||0),likes:Number(r.likes||0),comments:Number(r.comments||0),shares:Number(r.shares||0),signalScore:Number(r.signalScore||0),firstSeenAt:String(r.firstSeenAt||new Date().toISOString()),sourceUrl:evidence?.sourceUrl?String(evidence.sourceUrl):undefined,angle:String(evidence?.angle||'To be analyzed'),hook:String(evidence?.hook||String(r.headline||'')),verified:true}}
export async function saveAds(ads:Ad[]){const db=client();const unique=[...new Map(ads.map(a=>[a.id,a])).values()];const rows=unique.map(a=>({externalId:a.id,pageName:a.pageName,adText:a.adText,headline:a.headline,cta:a.cta,creativeUrl:a.creativeUrl||a.thumbnailUrl,creativeType:a.creativeType,thumbnailUrl:a.thumbnailUrl,landingUrl:a.landingUrl||null,country:a.country,firstSeenAt:new Date(a.firstSeenAt).toISOString(),lastSeenAt:new Date().toISOString(),daysActive:a.daysActive,isActive:true,likes:a.likes||0,comments:a.comments||0,shares:a.shares||0,signalScore:a.signalScore,evidence:{sourceUrl:a.sourceUrl,angle:a.angle,hook:a.hook}}));const{data,error}=await db.from('Ad').upsert(rows,{onConflict:'externalId'}).select();if(error)throw new Error(`Database save failed: ${error.message}`);return(data||[]).map(r=>rowToAd(r as Record<string,unknown>))}
export async function findAds(filters:{q?:string;country?:string;minDays?:number;mediaType?:string;sortBy?:string;page?:number;limit?:number}){const db=client(),limit=Math.min(filters.limit||30,100),page=Math.max(filters.page||1,1);let q=db.from('Ad').select('*',{count:'exact'}).eq('country',filters.country||'BD').gte('daysActive',filters.minDays||0);if(filters.q)q=q.or(`pageName.ilike.%${filters.q}%,adText.ilike.%${filters.q}%,headline.ilike.%${filters.q}%`);if(filters.mediaType&&filters.mediaType!=='ALL')q=q.eq('creativeType',filters.mediaType);const sort=filters.sortBy==='daysActive'?'daysActive':filters.sortBy==='newest'?'firstSeenAt':'signalScore';const{data,error,count}=await q.order(sort,{ascending:false}).range((page-1)*limit,page*limit-1);if(error)throw new Error(`Database query failed: ${error.message}`);return{ads:(data||[]).map(r=>rowToAd(r as Record<string,unknown>)),total:count||0}}
export async function findAd(id:string){const{data,error}=await client().from('Ad').select('*').or(`id.eq.${id},externalId.eq.${id}`).maybeSingle();if(error)throw new Error(error.message);return data?rowToAd(data as Record<string,unknown>):null}
export async function saveAnalysis(id:string,analysis:Analysis){const{error}=await client().from('Ad').update({aiAnalysis:analysis}).or(`id.eq.${id},externalId.eq.${id}`);if(error)throw new Error(error.message)}
export async function saveLandingAnalysis(id:string,analysis:LandingAnalysis){const{error}=await client().from('Ad').update({landingAnalysis:analysis}).or(`id.eq.${id},externalId.eq.${id}`);if(error)throw new Error(error.message)}
function rowToTikTok(r:Record<string,unknown>):TikTokAd{return{id:String(r.id),keyword:String(r.keyword||''),username:String(r.username||'TikTok creator'),caption:String(r.caption||''),videoUrl:String(r.videoUrl||''),thumbnailUrl:r.thumbnailUrl?String(r.thumbnailUrl):undefined,likes:Number(r.likes||0),views:Number(r.views||0),duration:Number(r.duration||0),musicName:r.musicName?String(r.musicName):undefined,videoId:r.videoId?String(r.videoId):undefined,country:String(r.country||'BD'),profitScore:Number(r.profitScore||0),firstSeen:String(r.firstSeen||r.createdAt||new Date().toISOString())}}
export async function saveTikTokAds(ads:TikTokAd[]){const rows=ads.map(a=>({id:a.id,keyword:a.keyword,username:a.username,caption:a.caption,videoUrl:a.videoUrl,thumbnailUrl:a.thumbnailUrl||null,likes:a.likes,views:a.views,duration:a.duration,musicName:a.musicName||null,videoId:a.videoId||null,country:a.country,profitScore:a.profitScore,firstSeen:new Date(a.firstSeen).toISOString()}));const{data,error}=await client().from('TikTokAd').upsert(rows,{onConflict:'id'}).select();if(error)throw new Error(error.message);return(data||[]).map(r=>rowToTikTok(r as Record<string,unknown>))}
export async function findTikTokAds(q='',limit=30){let query=client().from('TikTokAd').select('*').eq('country','BD').order('profitScore',{ascending:false}).limit(Math.min(limit,100));if(q)query=query.or(`keyword.ilike.%${q}%,caption.ilike.%${q}%,username.ilike.%${q}%`);const{data,error}=await query;if(error)throw new Error(error.message);return(data||[]).map(r=>rowToTikTok(r as Record<string,unknown>))}
export async function findAdsByIds(ids:string[]){if(!ids.length)return[];const{data,error}=await client().from('Ad').select('*').in('id',ids);if(error)throw new Error(error.message);return(data||[]).map(r=>rowToAd(r as Record<string,unknown>))}
export async function deleteIncompleteAds(){const db=client();const results=await Promise.all([db.from('Ad').delete().eq('pageName','Unknown advertiser').like('adText','Library ID:%'),db.from('Ad').delete().ilike('pageName','%ads use this creative%')]);const error=results.find(x=>x.error)?.error;if(error)throw new Error(`Incomplete-record cleanup failed: ${error.message}`)}
export async function testDatabase(){const{error}=await client().from('Ad').select('id',{head:true,count:'exact'}).limit(1);if(error)throw new Error(error.message);return true}
