import type{TikTokAd}from'./types';import{saveTikTokAds}from'./repository';
const clean=(v:unknown)=>typeof v==='string'?v:'';
const num=(v:unknown)=>Number(String(v??0).replace(/[^\d.]/g,''))||0;
function parse(items:unknown[],keyword:string):TikTokAd[]{return items.map((raw,index)=>{const r=raw as Record<string,any>,item=(r.item_info||r.ad_item||r)as Record<string,any>,stats=(item.statistics||item.stats||{})as Record<string,any>,video=(item.video_info||item.video||{})as Record<string,any>;const views=num(stats.play_count||stats.views||item.views),likes=num(stats.digg_count||stats.likes||item.likes),videoId=clean(item.item_id||item.id||item.video_id)||`live-${index}`;return{id:`tiktok-${videoId}`,keyword,username:clean(item.author_name||item.username||item.nick_name)||'TikTok creator',caption:clean(item.title||item.caption||item.desc)||`${keyword} creative`,videoUrl:clean(video.video_url||video.play_addr||item.video_url),thumbnailUrl:clean(video.cover||video.cover_url||item.thumbnail_url)||undefined,likes,views,duration:num(video.duration||item.duration),musicName:clean(item.music_title||item.music_name||item.music?.title)||undefined,videoId,country:'BD',profitScore:Math.round(views/1000+likes/100),firstSeen:new Date().toISOString()}}).filter(a=>a.videoUrl||a.thumbnailUrl)}
function mocks(keyword:string):TikTokAd[]{const hooks=['3 second freshness test','Office shoe confidence','Mosque-ready freshness','Gym bag rescue','Before vs after','POV: shoes smell gone','Bangladesh heat test','Customer reaction','Daily commute fix','One spray routine','Sock and shoe test','Fresh step challenge'];return hooks.map((hook,i)=>({id:`tiktok-mock-${encodeURIComponent(keyword)}-${i+1}`,keyword,username:`@bdcreative${i+1}`,caption:`${hook}: ${keyword} — short-form creative concept for the Bangladesh market.`,videoUrl:'',thumbnailUrl:`https://images.unsplash.com/photo-${['1542291026-7eec264c27ff','1549298916-b41d501d3772','1460353581641-37baddab0fa2'][i%3]}?auto=format&fit=crop&w=900&q=80`,likes:840+i*317,views:18200+i*4930,duration:15+i%4*5,musicName:i%2?'Original sound':'Trending BD audio',videoId:`demo-${i+1}`,country:'BD',profitScore:Math.round((18200+i*4930)/1000+(840+i*317)/100),firstSeen:new Date(Date.now()-i*86400000).toISOString(),isMock:true}))}
async function official(keyword:string){const url=`https://ads.tiktok.com/creative_radar_api/v1/top_ads/v2/list?country_code=BD&keyword=${encodeURIComponent(keyword)}&page=1&limit=30`;const r=await fetch(url,{headers:{accept:'application/json','user-agent':'Mozilla/5.0'},signal:AbortSignal.timeout(18000),cache:'no-store'});if(!r.ok)throw new Error(`TikTok API ${r.status}`);const json=await r.json()as Record<string,any>;const items=json.data?.materials||json.data?.list||json.data?.items||json.items||[];return parse(Array.isArray(items)?items:[],keyword)}
async function browserless(keyword:string){const token=process.env.BROWSERLESS_TOKEN;if(!token)return[];const target=`https://library.tiktok.com/search?query=${encodeURIComponent(keyword)}&country=BD`;const code=`export default async({page,context})=>{await page.goto(context.url,{waitUntil:'domcontentloaded',timeout:80000});await new Promise(r=>setTimeout(r,9000));for(let i=0;i<8;i++){await page.mouse.wheel({deltaY:600});await new Promise(r=>setTimeout(r,600))}const data=await page.evaluate(()=>[...document.querySelectorAll('video')].map((v,i)=>{const card=v.closest('article')||v.parentElement?.parentElement;const text=(card?.innerText||'').trim();return{id:'browser-'+i,username:(text.match(/@[\w.]+/)||[])[0]||'TikTok creator',caption:text.slice(0,500),videoUrl:v.currentSrc||v.src||'',thumbnailUrl:v.poster||'',views:0,likes:0,duration:Math.round(v.duration)||0}}));return{data,type:'application/json'}}`;const r=await fetch(`https://production-sfo.browserless.io/function?token=${encodeURIComponent(token)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,context:{url:target}}),signal:AbortSignal.timeout(100000)});if(!r.ok)return[];const json=await r.json()as Record<string,unknown>;return parse((json.data||json)as unknown[],keyword)}
export async function scrapeTikTokAds(keyword:string):Promise<TikTokAd[]>{let ads:TikTokAd[]=[];try{ads=await official(keyword)}catch{}if(!ads.length)try{ads=await browserless(keyword)}catch{}if(ads.length<10)ads=mocks(keyword);try{await saveTikTokAds(ads)}catch{}return ads}
export function mockTikTokAds(keyword:string){return mocks(keyword)}
